### ISSUE TITLE
Level setting is ignored in symfony

### ISSUE THREAD

**Issue by sebjac** [logtail/monolog-logtail#27]
Hi,

I followed the documentation and managed easily to send some logs with a test controller. The issue arised when I tried to change the level of logs sent. No matter the value set in the monolog.yaml file, it keeps the debug level.

current monolog conf set on a local environnement :
```yaml
monolog:
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: !php/const Monolog\Logger::INFO
            channels: ["!event"]
            max_files: 5
        better_stack:
            type: service
            id: Logtail\Monolog\LogtailHandler
            level: !php/const Monolog\Logger::WARNING
            channels: ["!event", "!doctrine", "!deprecation"]
```

The stack :
- symfony 6.4
- PHP 8.3
- Monolog 3.9
- Monolog Lotail 3.3

What am I missing ?

**Comment by sebjac** [comment]
Okay I figured it out. The level parameter has to be passed to the service config instead of the monolog config, like so :
```yaml
Logtail\Monolog\LogtailHandler:
    autoconfigure: true
    arguments:
        $sourceToken: '%env(BETTER_STACK_SOURCE_TOKEN)%'
        $endpoint: '%env(BETTER_STACK_SOURCE_ENDPOINT)%'
        $level: !php/const Monolog\Logger::WARNING
    tags:
        - { name: monolog.handler }

```
